### ISSUE TITLE
The training process stucked at the second epoch

### ISSUE THREAD

**Issue by xiaocongcsu** [fferroni/PointPillars#6]
My training process stucked at the second epoch, did anyone encounter this problem?

**Comment by raspbe34** [comment]
> My training process stucked at the second epoch, did anyone encounter this problem?

Did you have 'TypeError: only integer scalar arrays can be converted to a scalar index' message?

If then, i fixed it by changing on_epoch_end function in precessors.py.

from sklearn.utils import shuffle

def on_epoch_end(self):
                 self.lidar_files, self.label_files = shuffle(self.lidar_files, self.label_files)

**Comment by xiaocongcsu** [comment]
I solved the error as your advice! Thanks.

**Comment by tyagi-iiitv** [comment]
life savior :D
